//! Original GH-159 contract tests: CR 103/117/305/601/608/508–510/704.
//! Normal frozen-deck reset, seed 159/ordinal 0; no synthetic Game state.
use mtg_core::{
    episode::{Driver, Error, Progress, Status},
    game::{
        Config, DeckConfig, Game, actions, policy,
        terminal::{LossReason, Outcome},
    },
    objects::{Seat, Zone},
};
use serde_json::{Value, json};
use std::num::NonZeroUsize;
const CAP: usize = 256;
fn q() -> NonZeroUsize {
    NonZeroUsize::new(1).unwrap()
}
fn config() -> Config {
    let order = [
        ("bear-cub", 1),
        ("forest", 16),
        ("bear-cub", 3),
        ("giant-growth", 3),
        ("bite-down", 3),
        ("llanowar-elves", 3),
        ("druid-of-the-cowl", 2),
        ("magnigoth-sentry", 2),
        ("tajuru-pathwarden", 2),
        ("thornweald-archer", 3),
        ("wildheart-invoker", 2),
    ]
    .into_iter()
    .flat_map(|(k, n)| vec![k.to_string(); n])
    .collect();
    Config {
        seats: vec![
            DeckConfig {
                deck: "green".into(),
                order: Some(order)
            };
            2
        ],
        ..Config::default()
    }
}
fn settle(d: &mut Driver) {
    for _ in 0..300 {
        match d.advance(q()).unwrap() {
            Progress::InternalYield => (),
            _ => return,
        }
    }
    panic!("bounded fixture settlement");
}
fn normalized(bytes: &[u8]) -> Value {
    fn scrub(v: &mut Value) {
        match v {
            Value::Object(m) => {
                for (k, v) in m {
                    if k == "scope" || k == "store" {
                        *v = json!(0);
                    } else {
                        scrub(v)
                    }
                }
            }
            Value::Array(a) => {
                for v in a {
                    scrub(v)
                }
            }
            _ => (),
        }
    }
    let envelope: Value = serde_json::from_slice(bytes).unwrap();
    let mut v: Value = serde_json::from_str(envelope["payload"].as_str().unwrap()).unwrap();
    v["objects"]["id"] = json!(0);
    scrub(&mut v);
    v
}
fn reference(s: Seat, birth: u64, key: &str, zone: Zone, incarnation: u64) -> Value {
    json!({"birth":birth+if s==Seat::P0 {0} else {40},"card":key,"owner":s,"zone":zone,"incarnation":incarnation})
}
fn hand(s: Seat, n: u64, key: &str) -> Value {
    reference(s, n, key, Zone::Hand(s), 1)
}
fn permanent(s: Seat, n: u64, key: &str) -> Value {
    reference(
        s,
        n,
        key,
        Zone::Battlefield,
        if key == "forest" { 2 } else { 3 },
    )
}
struct Script {
    driver: Driver,
    replay: Game,
    expected: Vec<Value>,
    inject: bool,
}
impl Script {
    fn new(inject: bool) -> Self {
        let mut driver = Driver::new(CAP).unwrap();
        assert_eq!(
            driver.reset(&config(), 159, 0, q()),
            Ok(Progress::InternalYield)
        );
        assert!(driver.observe(Seat::P0).is_err());
        settle(&mut driver);
        let mut replay = Game::new().unwrap();
        replay.reset(&config(), 159, 0).unwrap();
        assert_eq!(
            normalized(&driver.privileged_snapshot()),
            normalized(&replay.snapshot())
        );
        Self {
            driver,
            replay,
            expected: vec![],
            inject,
        }
    }
    fn send(&mut self, s: Seat, kind: &str, choice: Value) {
        // This literal semantic record is the oracle, never generated by the driver.
        let expected = json!({"version":1,"actor":s,"decision":kind,"choices":[choice]});
        let bytes = serde_json::to_vec(&expected).unwrap();
        let actions::Decoded::Decision { mut submission, .. } =
            actions::decode(&self.replay, &bytes, CAP).unwrap()
        else {
            panic!()
        };
        let d = self.driver.observe(s).unwrap().decision.unwrap();
        assert_eq!(d.kind, kind);
        submission.revision = d.revision;
        submission.generation = d.generation;
        if self.inject {
            let snapshot = self.driver.privileged_snapshot();
            let history = self.driver.privileged_history().to_vec();
            let wrong = if s == Seat::P0 { Seat::P1 } else { Seat::P0 };
            assert!(self.driver.submit(wrong, &submission).is_err());
            for defect in 0..4 {
                let mut bad = submission.clone();
                match defect {
                    0 => bad.schema_version += 1,
                    1 => bad.revision += 1,
                    2 => bad.generation += 1,
                    _ => bad.choices.clear(),
                }
                assert!(self.driver.submit(s, &bad).is_err());
                assert_eq!(self.driver.privileged_snapshot(), snapshot);
                assert_eq!(self.driver.privileged_history(), history);
            }
        }
        self.driver.submit(s, &submission).unwrap();
        actions::apply(&mut self.replay, &bytes, CAP).unwrap();
        self.expected.push(expected);
        assert_eq!(self.driver.privileged_history().len(), self.expected.len());
        assert_eq!(
            serde_json::from_slice::<Value>(self.driver.privileged_history().last().unwrap())
                .unwrap(),
            *self.expected.last().unwrap()
        );
        if self.replay.outcome().is_none() {
            settle(&mut self.driver);
            if self.replay.decision().is_none() && self.replay.turn_position().is_none() {
                self.replay.start_turns().unwrap();
            }
        }
        assert_eq!(
            normalized(&self.driver.privileged_snapshot()),
            normalized(&self.replay.snapshot())
        );
    }
    fn idle(&mut self) {
        let s = self.replay.turn_decision().unwrap().actor;
        let kind = self.driver.observe(s).unwrap().decision.unwrap().kind;
        let choice = match kind {
            "priority" => json!({"kind":"pass"}),
            "attackers" | "blockers" | "combat_damage" => json!({"kind":"finish_combat"}),
            _ => panic!("unscripted {kind}"),
        };
        self.send(s, kind, choice);
    }
    fn until(&mut self, t: u64, step: &str) {
        for _ in 0..100 {
            if self
                .driver
                .observe(Seat::P0)
                .unwrap()
                .view
                .turn
                .is_some_and(|p| p.0 == t && p.2 == step)
            {
                return;
            }
            self.idle();
        }
        panic!("script bound {t} {step}")
    }
}
#[test]
fn normal_reset_literal_combat_history_and_rejected_interleavings() {
    let mut s = Script::new(true);
    for seat in [Seat::P0, Seat::P1] {
        s.send(seat, "keep_or_mulligan", json!({"kind":"keep"}));
    }
    assert_eq!(s.driver.observe(Seat::P0).unwrap().view.hand_counts, [7, 7]);
    assert_eq!(
        s.driver.observe(Seat::P0).unwrap().view.library_counts,
        [33, 33]
    );
    for turn in 1..=23 {
        let seat = if turn % 2 == 1 { Seat::P0 } else { Seat::P1 };
        s.until(turn, "precombat_main");
        s.send(
            seat,
            "priority",
            json!({"kind":"play_land","card":hand(seat,turn.div_ceil(2),"forest")}),
        );
        if turn == 3 {
            s.send(
                Seat::P0,
                "priority",
                json!({"kind":"cast","card":hand(Seat::P0,0,"bear-cub")}),
            );
            for n in [1, 2] {
                s.send(
                    Seat::P0,
                    "payment",
                    json!({"kind":"tap_mana","card":permanent(Seat::P0,n,"forest")}),
                );
            }
            for _ in 0..2 {
                s.send(Seat::P0, "payment", json!({"kind":"pay","color":4}));
            }
            s.send(Seat::P0, "payment", json!({"kind":"finish_payment"}));
            s.idle();
            s.idle();
            let view = s.driver.observe(Seat::P0).unwrap().view;
            let board = &view
                .public_zones
                .iter()
                .find(|z| z.zone == "battlefield")
                .unwrap()
                .cards;
            assert_eq!(
                board
                    .iter()
                    .filter(|c| c.card == "forest" && c.controller == 0 && c.tapped)
                    .count(),
                2
            );
            let cub = board.iter().find(|c| c.card == "bear-cub").unwrap();
            assert_eq!(cub.creature, Some([2, 2, 0]));
            assert!(cub.summoning_sick);
        }
        if turn >= 5 && turn % 2 == 1 {
            let hit = (turn - 3) / 2;
            s.until(turn, "declare_attackers");
            s.send(
                Seat::P0,
                "attackers",
                json!({"kind":"select_attackers","cards":[permanent(Seat::P0,0,"bear-cub")]}),
            );
            s.send(Seat::P0, "attackers", json!({"kind":"finish_combat"}));
            s.idle();
            s.idle();
            s.send(Seat::P1, "blockers", json!({"kind":"finish_combat"}));
            for _ in 0..10 {
                if s.replay.life()[1] == 20 - 2 * hit as i64 {
                    break;
                }
                s.idle();
            }
            assert_eq!(
                s.driver.observe(Seat::P0).unwrap().view.life,
                [20, 20 - 2 * hit as i64]
            );
        }
    }
    let outcome = Outcome {
        winner: Some(Seat::P0),
        losses: [None, Some(LossReason::Life)],
    };
    assert_eq!(s.replay.outcome(), Some(outcome));
    let before = s.driver.privileged_snapshot();
    let history = s.driver.privileged_history().to_vec();
    assert_eq!(s.driver.advance(q()), Err(Error::Ended));
    assert!(
        s.driver
            .concede(Seat::P0, s.driver.episode_id().unwrap())
            .is_err()
    );
    let bad = policy::Submission {
        schema_version: 1,
        revision: 0,
        generation: 0,
        choices: vec![policy::Choice::Pass],
    };
    assert!(s.driver.submit(Seat::P0, &bad).is_err());
    assert_eq!(s.driver.privileged_snapshot(), before);
    assert_eq!(s.driver.privileged_history(), history);
    let result = s.driver.finish().unwrap();
    assert_eq!(result.status(), Status::Completed(outcome));
    assert!(s.driver.finish().is_err());
    // Reapply the captured stream independently from normal reset, including RNG.
    let mut replay = Game::new().unwrap();
    replay.reset(&config(), 159, 0).unwrap();
    for b in result.privileged_history() {
        actions::apply(&mut replay, b, CAP).unwrap();
        if replay.decision().is_none()
            && replay.turn_position().is_none()
            && replay.outcome().is_none()
        {
            replay.start_turns().unwrap();
        }
    }
    assert_eq!(replay.life(), [20, 0]);
    assert_eq!(
        normalized(&replay.snapshot()),
        normalized(result.privileged_snapshot())
    );
    assert_eq!(
        s.expected
            .iter()
            .filter(|r| r["choices"][0]["kind"] == "play_land")
            .count(),
        23
    );
    assert_eq!(
        s.expected
            .iter()
            .filter(|r| r["choices"][0]["kind"] == "select_attackers")
            .count(),
        10
    );
}
#[test]
fn concession_incomplete_reset_and_owned_result_lifetime() {
    let mut s = Script::new(false);
    let stale = s.driver.observe(Seat::P0).unwrap().decision.unwrap();
    let old_id = s.driver.episode_id().unwrap();
    let before = s.driver.privileged_snapshot();
    assert_eq!(
        s.driver.reset(&config(), 2, 9, q()),
        Err(Error::ActiveEpisode)
    );
    assert_eq!(s.driver.privileged_snapshot(), before);
    // Nonacting seat can concede before making any decision (CR 104.3a).
    s.driver.concede(Seat::P1, old_id).unwrap();
    let a = s.driver.finish().unwrap();
    assert_eq!(
        a.status(),
        Status::Completed(Outcome {
            winner: Some(Seat::P0),
            losses: [None, Some(LossReason::Concession)]
        })
    );
    assert_eq!(a.privileged_history().len(), 1);
    assert_eq!(
        serde_json::from_slice::<Value>(&a.privileged_history()[0]).unwrap(),
        json!({"version":1,"actor":"P1","decision":"concession","choices":[{"kind":"concede"}]})
    );
    let saved = a.privileged_snapshot().to_vec();
    let saved_history = a.privileged_history().to_vec();
    let mut next = config();
    next.starting_seat = 1;
    s.driver.reset(&next, 888, 42, q()).unwrap();
    settle(&mut s.driver);
    let current = s.driver.privileged_snapshot();
    assert!(s.driver.concede(Seat::P0, old_id).is_err());
    let stale = policy::Submission {
        schema_version: 1,
        revision: stale.revision,
        generation: stale.generation,
        choices: vec![policy::Choice::Keep],
    };
    assert!(s.driver.submit(Seat::P1, &stale).is_err());
    assert_eq!(s.driver.privileged_snapshot(), current);
    assert!(s.driver.privileged_history().is_empty());
    let b = s.driver.finish().unwrap();
    assert_eq!(b.status(), Status::Incomplete);
    assert_eq!(
        (b.privileged_inputs().master, b.privileged_inputs().ordinal),
        (888, 42)
    );
    assert_eq!(b.privileged_inputs().config.starting_seat, 1);
    assert_eq!(
        (a.privileged_inputs().master, a.privileged_inputs().ordinal),
        (159, 0)
    );
    assert_eq!(a.privileged_snapshot(), saved);
    assert_eq!(a.privileged_history(), saved_history);
    assert_eq!(s.driver.advance(q()), Err(Error::Finalized));
}

#[test]
fn unfinished_yield_invalid_reset_and_real_shuffle_inputs() {
    let mut d = Driver::new(CAP).unwrap();
    assert_eq!(d.advance(q()), Err(Error::NotStarted));
    assert!(d.finish().is_err());
    let mut config = Config::default();
    d.reset(&config, 917, 3, q()).unwrap();
    let unfinished = d.privileged_snapshot();
    let a = d.finish().unwrap();
    assert_eq!(a.status(), Status::Incomplete);
    assert_eq!(a.privileged_snapshot(), unfinished);
    config.format = "not-supported".into();
    assert!(d.reset(&config, 0, 0, q()).is_err());
    assert_eq!(d.privileged_snapshot(), unfinished);
    assert!(d.privileged_history().is_empty());
    config.format = mtg_core::game::FORMAT.into();
    d.reset(&config, 917, 3, q()).unwrap();
    settle(&mut d);
    let mut replay = Game::new().unwrap();
    replay.reset(&config, 917, 3).unwrap();
    assert_eq!(
        normalized(&d.privileged_snapshot()),
        normalized(&replay.snapshot())
    );
    let b = d.finish().unwrap();
    assert_eq!(b.status(), Status::Incomplete);
    config.starting_seat = 1;
    assert_eq!(b.privileged_inputs().config.starting_seat, 0);
    assert_eq!(
        (b.privileged_inputs().master, b.privileged_inputs().ordinal),
        (917, 3)
    );
    assert_eq!(a.privileged_snapshot(), unfinished);
    // Actual shuffle consumes RNG; an unfinished reset remains distinct.
    assert_ne!(
        normalized(a.privileged_snapshot()),
        normalized(b.privileged_snapshot())
    );
}

#[test]
fn seat_observations_and_capacity_failure_are_nonmutating() {
    let mut d = Driver::new(CAP).unwrap();
    d.reset(&Config::default(), 159, 1, NonZeroUsize::MAX)
        .unwrap();
    let p0 = d.observe(Seat::P0).unwrap();
    let p1 = d.observe(Seat::P1).unwrap();
    assert_eq!(p0.view.hand.len(), 7);
    assert_eq!(p1.view.hand.len(), 7);
    assert!(p0.view.hand.iter().all(|c| c.owner == 0));
    assert!(p1.view.hand.iter().all(|c| c.owner == 1));
    assert!(p0.decision.is_some());
    assert!(p1.decision.is_none());
    for obs in [p0, p1] {
        let v = serde_json::to_value(obs).unwrap();
        for key in ["rng", "master", "history", "snapshot", "config"] {
            assert!(v.get(key).is_none());
        }
    }
    let mut small = Driver::new(0).unwrap();
    small.reset(&config(), 159, 0, NonZeroUsize::MAX).unwrap();
    let before = small.privileged_snapshot();
    assert!(small.observe(Seat::P0).is_err());
    let submission = policy::Submission {
        schema_version: 1,
        revision: 1,
        generation: 1,
        choices: vec![policy::Choice::Keep],
    };
    assert!(small.submit(Seat::P0, &submission).is_err());
    assert_eq!(small.privileged_snapshot(), before);
    assert!(small.privileged_history().is_empty());
}

#[test]
fn concession_during_yielding_reset_is_rejected_then_settled_history_replays() {
    // A completed result must be reproducible from normal reset inputs/history.
    // CR 104.3a does not require this API to expose partial internal reset state.
    let mut d = Driver::new(CAP).unwrap();
    d.reset(&Config::default(), 159, 7, q()).unwrap();
    let id = d.episode_id().unwrap();
    let before = d.privileged_snapshot();
    for seat in [Seat::P0, Seat::P1] {
        assert_eq!(
            d.concede(seat, id),
            Err(Error::Concede(
                mtg_core::game::terminal::ConcedeError::SettlementPending
            ))
        );
        assert_eq!(d.privileged_snapshot(), before);
        assert!(d.privileged_history().is_empty());
    }
    settle(&mut d);
    d.concede(Seat::P1, id).unwrap();
    let result = d.finish().unwrap();
    assert_eq!(result.privileged_history().len(), 1);
    let mut replay = Game::new().unwrap();
    replay.reset(&Config::default(), 159, 7).unwrap();
    actions::apply(&mut replay, &result.privileged_history()[0], CAP).unwrap();
    assert_eq!(
        replay.outcome(),
        Some(Outcome {
            winner: Some(Seat::P0),
            losses: [None, Some(LossReason::Concession)]
        })
    );
    assert_eq!(
        normalized(result.privileged_snapshot()),
        normalized(&replay.snapshot())
    );
}

#[test]
fn opening_to_turn_yields_reject_concession_until_a_replayable_boundary() {
    let mut d = Driver::new(CAP).unwrap();
    d.reset(&config(), 159, 0, NonZeroUsize::MAX).unwrap();
    for seat in [Seat::P0, Seat::P1] {
        let decision = d.observe(seat).unwrap().decision.unwrap();
        d.submit(
            seat,
            &policy::Submission {
                schema_version: 1,
                revision: decision.revision,
                generation: decision.generation,
                choices: vec![policy::Choice::Keep],
            },
        )
        .unwrap();
    }
    // No automatic advance here: second Keep leaves the opening-to-turn gap.
    let id = d.episode_id().unwrap();
    for _ in 0..20 {
        let before = d.privileged_snapshot();
        let history = d.privileged_history().to_vec();
        for seat in [Seat::P0, Seat::P1] {
            assert_eq!(
                d.concede(seat, id),
                Err(Error::Concede(
                    mtg_core::game::terminal::ConcedeError::SettlementPending
                ))
            );
            assert_eq!(d.privileged_snapshot(), before);
            assert_eq!(d.privileged_history(), history);
        }
        if d.advance(q()).unwrap() == Progress::Ready {
            break;
        }
    }
    assert_eq!(
        d.observe(Seat::P0).unwrap().view.turn,
        Some((1, 0, "upkeep"))
    );
    d.concede(Seat::P1, id).unwrap();
    let result = d.finish().unwrap();
    assert_eq!(result.privileged_history().len(), 3);
    let mut replay = Game::new().unwrap();
    replay.reset(&config(), 159, 0).unwrap();
    for record in result.privileged_history() {
        actions::apply(&mut replay, record, CAP).unwrap();
        if replay.decision().is_none()
            && replay.turn_position().is_none()
            && replay.outcome().is_none()
        {
            replay.start_turns().unwrap();
        }
    }
    assert_eq!(replay.life(), [20, 20]);
    assert_eq!(replay.outcome().unwrap().winner, Some(Seat::P0));
    assert_eq!(
        normalized(result.privileged_snapshot()),
        normalized(&replay.snapshot())
    );
}

#[test]
fn concession_at_ready_payment_boundary_remains_recorded_and_replayable() {
    let mut s = Script::new(false);
    for seat in [Seat::P0, Seat::P1] {
        s.send(seat, "keep_or_mulligan", json!({"kind":"keep"}));
    }
    for turn in 1..=3 {
        let seat = if turn % 2 == 1 { Seat::P0 } else { Seat::P1 };
        s.until(turn, "precombat_main");
        s.send(
            seat,
            "priority",
            json!({"kind":"play_land","card":hand(seat,turn.div_ceil(2),"forest")}),
        );
    }
    s.send(
        Seat::P0,
        "priority",
        json!({"kind":"cast","card":hand(Seat::P0,0,"bear-cub")}),
    );
    assert_eq!(
        s.driver.observe(Seat::P0).unwrap().decision.unwrap().kind,
        "payment"
    );
    s.driver
        .concede(Seat::P1, s.driver.episode_id().unwrap())
        .unwrap();
    let result = s.driver.finish().unwrap();
    let record = result.privileged_history().last().unwrap();
    actions::apply(&mut s.replay, record, CAP).unwrap();
    assert_eq!(s.replay.outcome().unwrap().winner, Some(Seat::P0));
    assert_eq!(
        normalized(result.privileged_snapshot()),
        normalized(&s.replay.snapshot())
    );
}
