//! CR 601.2c/f/h/i, 117.3/4, 608.2b/h; frozen Growth (+3/+3) and Bite
//! (source deals its current power). Expected states are literal, not snapshots
//! generated by the implementation. Setup below is explicitly synthetic;
//! every action after setup uses the actual safe policy boundary.
use super::*;
fn add(g: &mut Game, key: &str, s: Seat, zone: Zone) {
    g.objects
        .allocate(CardId::from_key(key).unwrap(), s, zone)
        .unwrap();
}
fn position(hidden: bool) -> Game {
    let mut g = game(Seat::P0, hidden);
    keep(&mut g, Seat::P0);
    g.turns.position = Some((1, Seat::P0, turns::Step::PrecombatMain));
    for s in [Seat::P0, Seat::P1] {
        add(&mut g, "bear-cub", s, Zone::Battlefield);
        add(&mut g, "forest", s, Zone::Battlefield);
        add(&mut g, "forest", s, Zone::Battlefield);
        for key in ["giant-growth", "bite-down"] {
            add(&mut g, key, s, Zone::Hand(s));
        }
    }
    g
}
fn wire(kind: &str, card: Option<VisibleRef>) -> Choice {
    let mut v = serde_json::json!({"kind":kind});
    if let Some(r) = card {
        v["card"] = serde_json::to_value(r).unwrap();
    }
    serde_json::from_value(v).unwrap()
}
fn hand(g: &Game, s: Seat, key: &str) -> VisibleRef {
    reference(
        VisibleZone::Hand,
        g.policy_observe(s, CAP)
            .unwrap()
            .view
            .hand
            .iter()
            .position(|c| c.card == key)
            .unwrap(),
    )
}
fn action(g: &mut Game, s: Seat, kind: &str, card: Option<VisibleRef>) {
    submit(g, s, vec![wire(kind, card)]).unwrap();
}
fn cast(g: &mut Game, s: Seat, key: &str, targets: &[usize]) {
    // This assertion also produces a compiled behavioral red on the old API.
    let o = g.policy_observe(s, CAP).unwrap();
    assert!(
        serde_json::to_string(&o.decision)
            .unwrap()
            .contains("\"cast\"")
    );
    action(g, s, "cast", Some(hand(g, s, key)));
    for &row in targets {
        action(
            g,
            s,
            "target",
            Some(reference(VisibleZone::Battlefield, row)),
        );
    }
    action(g, s, "finish_targets", None);
}
fn pay(g: &mut Game, s: Seat, lands: &[usize]) {
    for &row in lands {
        action(
            g,
            s,
            "tap_mana",
            Some(reference(VisibleZone::Battlefield, row)),
        );
    }
    for _ in lands {
        submit(g, s, vec![Choice::Pay { color: 4 }]).unwrap();
    }
    action(g, s, "finish_payment", None);
}
fn json(g: &Game, s: Seat) -> serde_json::Value {
    serde_json::to_value(g.policy_observe(s, CAP).unwrap()).unwrap()
}
fn reject(g: &mut Game, s: Seat, c: Choice, error: PolicyError) {
    let d = g.policy_observe(Seat::P0, CAP).unwrap().decision.unwrap();
    unchanged(
        g,
        s,
        Submission {
            schema_version: 1,
            revision: d.revision,
            generation: d.generation,
            choices: vec![c],
        },
        CAP,
        error,
    );
}
#[test]
fn policy_spells_twins_cancel_each_stage_and_reject_without_mutation() {
    let mut a = position(false);
    let mut b = position(true);
    assert_eq!(
        a.policy_observe(Seat::P0, CAP),
        b.policy_observe(Seat::P0, CAP)
    );
    let mut traces = vec![];
    for g in [&mut a, &mut b] {
        let mut trace = vec![];
        let public = g.policy_observe(Seat::P1, CAP).unwrap();
        let committed = g.observe_visible_state(Seat::P0).unwrap();
        for stage in 0..6 {
            action(g, Seat::P0, "cast", Some(hand(g, Seat::P0, "bite-down")));
            assert_eq!(
                g.policy_observe(Seat::P0, CAP)
                    .unwrap()
                    .decision
                    .unwrap()
                    .kind,
                "bite_source"
            );
            reject(
                g,
                Seat::P0,
                wire("target", Some(reference(VisibleZone::Battlefield, 3))),
                PolicyError::InvalidSelection,
            );
            reject(
                g,
                Seat::P0,
                wire("target", Some(reference(VisibleZone::Hand, 0))),
                PolicyError::InvalidSelection,
            );
            reject(
                g,
                Seat::P0,
                wire("target", Some(reference(VisibleZone::Battlefield, 999))),
                PolicyError::InvalidSelection,
            );
            reject(
                g,
                Seat::P1,
                wire("cancel_targets", None),
                PolicyError::WrongActor,
            );
            let old = g.policy_observe(Seat::P0, CAP).unwrap().decision.unwrap();
            if stage > 0 {
                action(
                    g,
                    Seat::P0,
                    "target",
                    Some(reference(VisibleZone::Battlefield, 0)),
                );
            }
            if stage > 1 {
                action(
                    g,
                    Seat::P0,
                    "target",
                    Some(reference(VisibleZone::Battlefield, 3)),
                );
            }
            if stage > 2 {
                action(g, Seat::P0, "finish_targets", None);
            }
            if stage > 3 {
                action(
                    g,
                    Seat::P0,
                    "tap_mana",
                    Some(reference(VisibleZone::Battlefield, 1)),
                );
            }
            if stage > 4 {
                submit(g, Seat::P0, vec![Choice::Pay { color: 4 }]).unwrap();
            }
            trace.push(g.policy_observe(Seat::P0, CAP).unwrap());
            assert_eq!(g.policy_observe(Seat::P1, CAP).unwrap(), public);
            assert_eq!(g.observe_visible_state(Seat::P0).unwrap(), committed);
            if stage > 0 {
                unchanged(
                    g,
                    Seat::P0,
                    Submission {
                        schema_version: 1,
                        revision: old.revision,
                        generation: old.generation,
                        choices: vec![wire("target", Some(reference(VisibleZone::Battlefield, 0)))],
                    },
                    CAP,
                    PolicyError::StaleDecision,
                );
            }
            if stage > 2 {
                reject(
                    g,
                    Seat::P0,
                    Choice::FinishPayment,
                    PolicyError::InvalidSelection,
                );
            }
            action(
                g,
                Seat::P0,
                if stage > 2 {
                    "cancel_payment"
                } else {
                    "cancel_targets"
                },
                None,
            );
            assert_eq!(g.observe_visible_state(Seat::P0).unwrap(), committed);
        }
        traces.push(trace);
    }
    assert_eq!(traces[0], traces[1]);
    assert_eq!(
        a.policy_observe(Seat::P0, CAP),
        b.policy_observe(Seat::P0, CAP)
    );
}
#[test]
fn policy_spells_growth_response_to_bite_and_public_targets() {
    for hidden in [false, true] {
        let mut g = position(hidden);
        cast(&mut g, Seat::P0, "bite-down", &[0, 3]);
        let private = json(&g, Seat::P0);
        assert_eq!(
            private["pending"]["targets"],
            serde_json::json!([{"zone":"battlefield","row":0},{"zone":"battlefield","row":3}])
        );
        assert!(json(&g, Seat::P1)["pending"].is_null());
        pay(&mut g, Seat::P0, &[1, 2]);
        let public = json(&g, Seat::P1);
        assert_eq!(public["stack"][0]["targets"], private["pending"]["targets"]);
        pass(&mut g);
        cast(&mut g, Seat::P1, "giant-growth", &[3]);
        pay(&mut g, Seat::P1, &[4]);
        assert_eq!(json(&g, Seat::P0)["stack"].as_array().unwrap().len(), 2);
        pass(&mut g);
        pass(&mut g);
        assert_eq!(
            g.policy_observe(Seat::P0, CAP).unwrap().view.public_zones[2].cards[3].creature,
            Some([5, 5, 0])
        );
        pass(&mut g);
        pass(&mut g);
        let o = g.policy_observe(Seat::P0, CAP).unwrap();
        assert_eq!(o.view.public_zones[2].cards[3].creature, Some([5, 5, 2]));
        assert_eq!(o.view.public_zones[2].cards[0].creature, Some([2, 2, 0]));
        assert!(json(&g, Seat::P0)["stack"].as_array().unwrap().is_empty());
    }
}
#[test]
fn policy_spells_partial_invalidation_by_real_response_has_no_source_lki() {
    let mut g = position(false);
    cast(&mut g, Seat::P0, "bite-down", &[0, 3]);
    pay(&mut g, Seat::P0, &[1, 2]);
    pass(&mut g);
    cast(&mut g, Seat::P1, "bite-down", &[3, 0]);
    pay(&mut g, Seat::P1, &[4, 5]);
    pass(&mut g);
    pass(&mut g);
    let v = json(&g, Seat::P0);
    assert!(v["stack"][0]["targets"][0].is_null());
    assert_eq!(
        v["stack"][0]["targets"][1],
        serde_json::json!({"zone":"battlefield","row":2})
    );
    pass(&mut g);
    pass(&mut g);
    assert_eq!(g.last_resolution().unwrap().legal_targets, 1);
    assert!(g.last_resolution().unwrap().resolved);
    assert_eq!(
        g.policy_observe(Seat::P0, CAP).unwrap().view.public_zones[2].cards[2].creature,
        Some([2, 2, 0])
    );
}
#[test]
fn policy_spells_all_generic_colors_preserved_and_finish_requires_paid_cost() {
    // Synthetic pool explores all six colors independently; CR 107.4 permits
    // G plus each one of WUBRGC for 1G. Only R/G sources exist in this pool.
    for color in 0..6 {
        let mut g = position(false);
        g.turns.mana[0] = [1, 1, 1, 1, 2, 1];
        cast(&mut g, Seat::P0, "bite-down", &[0, 3]);
        submit(&mut g, Seat::P0, vec![Choice::Pay { color: 4 }]).unwrap();
        let d = g.policy_observe(Seat::P0, CAP).unwrap().decision.unwrap();
        for c in 0..6 {
            let i = d
                .candidates
                .iter()
                .position(|x| *x == Choice::Pay { color: c })
                .unwrap();
            assert!(d.legal_mask[i]);
        }
        submit(&mut g, Seat::P0, vec![Choice::Pay { color }]).unwrap();
        action(&mut g, Seat::P0, "finish_payment", None);
        let mut expected = [1, 1, 1, 1, 1, 1];
        expected[usize::from(color)] -= 1;
        assert_eq!(g.mana()[0], expected);
    }
}

#[test]
fn policy_spells_normal_reset_twins_real_lands_creatures_bite_and_cancel() {
    for response in [false, true] {
        let mut outcomes = vec![];
        for hidden in [false, true] {
            let manifest: serde_json::Value = serde_json::from_str(include_str!(
                "../../../data/cards/foundations_micro_v1.json"
            ))
            .unwrap();
            let deck = manifest["decks"]
                .as_array()
                .unwrap()
                .iter()
                .find(|d| d["id"] == "green")
                .unwrap();
            let mut order: Vec<String> = [
                "bear-cub",
                "bite-down",
                "giant-growth",
                "forest",
                "forest",
                "forest",
                "forest",
            ]
            .into_iter()
            .map(String::from)
            .collect();
            for c in deck["cards"].as_array().unwrap() {
                let key = c["card_id"].as_str().unwrap();
                for _ in order.iter().filter(|s| s.as_str() == key).count()
                    ..c["copies"].as_u64().unwrap() as usize
                {
                    order.push(key.into());
                }
            }
            let mut other_order = order.clone();
            if hidden {
                other_order[9..].reverse();
            } // Unseen tail only; draws through turn four are fixed.
            let mut g = Game::new().unwrap();
            g.reset(
                &Config {
                    seats: vec![
                        DeckConfig {
                            deck: "green".into(),
                            order: Some(order),
                        },
                        DeckConfig {
                            deck: "green".into(),
                            order: Some(other_order),
                        },
                    ],
                    ..Config::default()
                },
                42,
                0,
            )
            .unwrap();
            keep(&mut g, Seat::P0);
            for turn in 1..=4 {
                let s = if turn % 2 == 1 { Seat::P0 } else { Seat::P1 };
                for _ in 0..40 {
                    if g.turn_position() == Some((turn, s, turns::Step::PrecombatMain)) {
                        break;
                    }
                    pass(&mut g);
                }
                assert_eq!(
                    g.turn_position(),
                    Some((turn, s, turns::Step::PrecombatMain))
                );
                let r = hand(&g, s, "forest");
                action(&mut g, s, "play_land", Some(r));
                if turn == 3 || (turn == 4 && !response) {
                    for _ in 0..30 {
                        if g.turn_position() == Some((turn, s, turns::Step::PostcombatMain)) {
                            break;
                        }
                        pass(&mut g);
                    }
                    assert_eq!(
                        g.turn_position(),
                        Some((turn, s, turns::Step::PostcombatMain))
                    );
                    let r = hand(&g, s, "bear-cub");
                    action(&mut g, s, "cast", Some(r));
                    let o = g.policy_observe(s, CAP).unwrap();
                    let lands: Vec<_> = o.view.public_zones[2]
                        .cards
                        .iter()
                        .enumerate()
                        .filter(|(_, c)| c.controller == seat_index(s) as u8 && c.card == "forest")
                        .map(|(i, _)| i)
                        .collect();
                    pay(&mut g, s, &lands);
                    pass(&mut g);
                    pass(&mut g);
                }
            }
            for _ in 0..40 {
                if g.turn_position() == Some((5, Seat::P0, turns::Step::Upkeep)) {
                    break;
                }
                pass(&mut g);
            }
            assert_eq!(g.turn_position(), Some((5, Seat::P0, turns::Step::Upkeep)));
            if response {
                cast(&mut g, Seat::P0, "giant-growth", &[3]);
                pay(&mut g, Seat::P0, &[0]);
                pass(&mut g);
                cast(&mut g, Seat::P1, "giant-growth", &[3]);
                pay(&mut g, Seat::P1, &[1]);
                pass(&mut g);
                pass(&mut g);
                assert_eq!(
                    g.policy_observe(Seat::P0, CAP).unwrap().view.public_zones[2].cards[3].creature,
                    Some([5, 5, 0])
                );
                pass(&mut g);
                pass(&mut g);
                assert_eq!(
                    g.policy_observe(Seat::P0, CAP).unwrap().view.public_zones[2].cards[3].creature,
                    Some([8, 8, 0])
                );
                outcomes.push(g.policy_observe(Seat::P0, CAP).unwrap());
                continue;
            }
            // Public battlefield order: P0 land, P1 land, P0 land, P0 Cub,
            // P1 land, P1 Cub. Canceling provisional Bite preserves all of it.
            let before = g.policy_observe(Seat::P1, CAP).unwrap();
            cast(&mut g, Seat::P0, "bite-down", &[3, 5]);
            action(
                &mut g,
                Seat::P0,
                "tap_mana",
                Some(reference(VisibleZone::Battlefield, 0)),
            );
            submit(&mut g, Seat::P0, vec![Choice::Pay { color: 4 }]).unwrap();
            action(&mut g, Seat::P0, "cancel_payment", None);
            assert_eq!(g.policy_observe(Seat::P1, CAP).unwrap(), before);
            cast(&mut g, Seat::P0, "bite-down", &[3, 5]);
            pay(&mut g, Seat::P0, &[0, 2]);
            pass(&mut g);
            // P1's lands are tapped from the preceding creature cast, so Growth
            // must be funded before that cast: this script instead tests the caster
            // retaining priority and a response once P1's next untap has occurred.
            // Here the legal response is unavailable and must remain masked.
            let d = g.policy_observe(Seat::P1, CAP).unwrap().decision.unwrap();
            let growth = wire("cast", Some(hand(&g, Seat::P1, "giant-growth")));
            assert!(!d.legal_mask[d.candidates.iter().position(|c| *c == growth).unwrap()]);
            pass(&mut g);
            assert_eq!(g.last_resolution().unwrap().legal_targets, 2);
            assert!(
                g.policy_observe(Seat::P0, CAP).unwrap().view.public_zones[1]
                    .cards
                    .iter()
                    .any(|c| c.card == "bear-cub")
            );
            outcomes.push(g.policy_observe(Seat::P0, CAP).unwrap());
        }
        assert_eq!(outcomes[0], outcomes[1]);
    }
}

#[test]
fn policy_spells_capacity_masks_stale_and_wrong_seat_at_every_stage() {
    let mut g = position(false);
    let r = hand(&g, Seat::P0, "bite-down");
    action(&mut g, Seat::P0, "cast", Some(r));
    let sequence = [
        wire("target", Some(reference(VisibleZone::Battlefield, 0))),
        wire("target", Some(reference(VisibleZone::Battlefield, 3))),
        wire("finish_targets", None),
        wire("tap_mana", Some(reference(VisibleZone::Battlefield, 1))),
        Choice::Pay { color: 4 },
        wire("tap_mana", Some(reference(VisibleZone::Battlefield, 2))),
        Choice::Pay { color: 4 },
        Choice::FinishPayment,
    ];
    for choice in sequence {
        let d = g.policy_observe(Seat::P0, CAP).unwrap().decision.unwrap();
        let request = Submission {
            schema_version: 1,
            revision: d.revision,
            generation: d.generation,
            choices: vec![choice],
        };
        assert!(g.policy_observe(Seat::P0, d.candidates.len()).is_ok());
        assert_eq!(
            g.policy_observe(Seat::P0, d.candidates.len() - 1),
            Err(PolicyError::CapacityExceeded)
        );
        unchanged(
            &mut g,
            Seat::P0,
            request.clone(),
            d.candidates.len() - 1,
            PolicyError::CapacityExceeded,
        );
        unchanged(
            &mut g,
            Seat::P1,
            request.clone(),
            CAP,
            PolicyError::WrongActor,
        );
        for (c, legal) in d.candidates.iter().zip(d.legal_mask.iter()) {
            if !legal {
                unchanged(
                    &mut g,
                    Seat::P0,
                    Submission {
                        choices: vec![c.clone()],
                        ..request.clone()
                    },
                    CAP,
                    PolicyError::InvalidSelection,
                );
            }
        }
        for c in [
            wire("target", Some(reference(VisibleZone::Hand, 999))),
            Choice::Pay { color: 255 },
        ] {
            unchanged(
                &mut g,
                Seat::P0,
                Submission {
                    choices: vec![c],
                    ..request.clone()
                },
                CAP,
                PolicyError::InvalidSelection,
            );
        }
        g.apply_policy(Seat::P0, &request, CAP).unwrap();
        unchanged(&mut g, Seat::P0, request, CAP, PolicyError::StaleDecision);
    }
    assert_eq!(g.objects.in_zone(Zone::Stack).count(), 1);
    assert_eq!(g.mana()[0], [0; 6]);
}
